#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative 'lexer'
  require 'logging'

module Calculator
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 19)
  def initialize
    @logger = Logging.logger[self]
  end

  attr_reader :log

  def parse(tokens)
    @tokens = tokens

    do_parse
  end

  def next_token
    @tokens.shift
  end
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
     5,     6,     7,     8,     5,     6,     7,     8,    11,     3,
    10,     4,    12,    13,    14,     3 ]

racc_action_check = [
     9,     9,     9,     9,     2,     2,     2,     2,     5,     3,
     4,     1,     6,     7,     8,     0 ]

racc_action_pointer = [
    13,    11,     1,     7,    10,     6,    10,    11,    12,    -3,
   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -8,    -8,    -1,    -2,    -8,    -8,    -8,    -8,    -8,    -3,
    15,    -4,    -5,    -6,    -7 ]

racc_goto_table = [
     2,     1,   nil,     9 ]

racc_goto_check = [
     2,     1,   nil,     2 ]

racc_goto_pointer = [
   nil,     1,     0 ]

racc_goto_default = [
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 8, :_reduce_none,
  1, 9, :_reduce_2,
  2, 9, :_reduce_3,
  3, 9, :_reduce_4,
  3, 9, :_reduce_5,
  3, 9, :_reduce_6,
  3, 9, :_reduce_7 ]

racc_reduce_n = 8

racc_shift_n = 15

racc_token_table = {
  false => 0,
  :error => 1,
  :DIGIT => 2,
  :ADD => 3,
  :SUBTRACT => 4,
  :MULTIPLY => 5,
  :DIVIDE => 6 }

racc_nt_base = 7

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DIGIT",
  "ADD",
  "SUBTRACT",
  "MULTIPLY",
  "DIVIDE",
  "$start",
  "target",
  "expression" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'parser.racc', 5)
  def _reduce_2(val, _values, result)
     @logger.debug "M DIGIT #{val.to_s}"; return val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 6)
  def _reduce_3(val, _values, result)
     @logger.debug "M #{val.to_s}"; return val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 7)
  def _reduce_4(val, _values, result)
     @logger.debug "M ADD #{val.to_s}"; return val[0] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 8)
  def _reduce_5(val, _values, result)
     @logger.debug "M SUB #{val.to_s}"; return val[0] - val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 9)
  def _reduce_6(val, _values, result)
     @logger.debug "M MUL #{val.to_s}"; return val[0] * val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 10)
  def _reduce_7(val, _values, result)
     @logger.debug "M DIV #{val.to_s}"; return val[0] / val[2] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Calculator
